### PR TITLE
Add basic network troubleshooting tools to the base image

### PR DESCRIPTION
**Pull request by tcptomato**
The container lacks ping / traceroute / ip commands which are useful when debugging network issues. This PR adds them.

Signed-off-by: Thomas Böhm <thomas.boehm@hensoldt-cyber.de>

### CODE REVIEW

**Comment by axel-h** [comment]
The automatic checks complain about `apply-rust.sh:35`, seem unrelated to this PR?

**Comment by lsf37** [comment]
> The automatic checks complain about `apply-rust.sh:35`, seem unrelated to this PR?

Yes, the linter in this one is not scoped to the pull request. I'll add an issue to see if that is possible to do.

**Review by lsf37 — APPROVED** [review]
Yes, I think these would be quite useful to have and they don't add too much size.

**Comment by tcptomato** [comment]
@axel-h It's unrelated.

@lsf37 Thanks.

**Pull request merged**
